dataset_name: bcic2b_within
max_epochs: 1000
model: BaseNet
model_kwargs:
  ch_dim: 16
  dropout: 0.5
  dropout_inp: 0.5
  input_window_samples: 1000
  label_smoothing: 0.0
  lr: 0.001
  n_channels: 3
  n_classes: 2
  n_temporal_filters: 40
  optimizer: adam
  pool_length: 8
  pool_length_inp: 75
  pool_stride: 8
  pool_stride_inp: 15
  scheduler: true
  spatial_expansion: 1
  temp_filter_length: 15
  temp_filter_length_inp: 25
  warmup_epochs: 20
  weight_decay: 0.0
preprocessing:
  alignment: false
  batch_size: 64
  high_cut: 40
  low_cut: 0
  sfreq: 250
  start: 0.0
  stop: -0.5
seed: 0
subject_ids: all
